// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/shopspring/decimal"
)

type Portfolio struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type Position struct {
	ID          int64
	PortfolioID int64
	Ticker      string
	Quantity    int64
	AvgPrice    decimal.Decimal
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
