// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolios.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const createPortfolio = `-- name: CreatePortfolio :one

INSERT INTO portfolios (name)
VALUES ($1)
RETURNING id, name, created_at
`

// Запросы к портфелям и позициям.
//
// Каждый запрос начинается с аннотации sqlc: "-- name: <ИмяМетода> <режим>".
// Режимы: :one (одна строка), :many (слайс), :exec (без результата),
// :execrows (вернуть число затронутых строк).
// Параметры: $1, $2 или именованные sqlc.arg(name) — из них получатся
// поля структуры параметров в Go.
func (q *Queries) CreatePortfolio(ctx context.Context, name string) (Portfolio, error) {
	row := q.db.QueryRow(ctx, createPortfolio, name)
	var i Portfolio
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deletePosition = `-- name: DeletePosition :execrows
DELETE FROM positions
WHERE portfolio_id = $1 AND ticker = $2
`

type DeletePositionParams struct {
	PortfolioID int64
	Ticker      string
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePosition, arg.PortfolioID, arg.Ticker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPortfolio = `-- name: GetPortfolio :one
SELECT id, name, created_at
FROM portfolios
WHERE id = $1
`

func (q *Queries) GetPortfolio(ctx context.Context, id int64) (Portfolio, error) {
	row := q.db.QueryRow(ctx, getPortfolio, id)
	var i Portfolio
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listPortfolios = `-- name: ListPortfolios :many
SELECT id, name, created_at
FROM portfolios
ORDER BY id
`

func (q *Queries) ListPortfolios(ctx context.Context) ([]Portfolio, error) {
	rows, err := q.db.Query(ctx, listPortfolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, portfolio_id, ticker, quantity, avg_price, created_at, updated_at
FROM positions
WHERE portfolio_id = $1
ORDER BY ticker
`

func (q *Queries) ListPositions(ctx context.Context, portfolioID int64) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Ticker,
			&i.Quantity,
			&i.AvgPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosition = `-- name: UpsertPosition :one
INSERT INTO positions (portfolio_id, ticker, quantity, avg_price)
VALUES ($1, $2, $3, $4)
ON CONFLICT (portfolio_id, ticker) DO UPDATE
SET quantity   = EXCLUDED.quantity,
    avg_price  = EXCLUDED.avg_price,
    updated_at = now()
RETURNING id, portfolio_id, ticker, quantity, avg_price, created_at, updated_at
`

type UpsertPositionParams struct {
	PortfolioID int64
	Ticker      string
	Quantity    int64
	AvgPrice    decimal.Decimal
}

// UpsertPosition создаёт позицию или полностью заменяет количество и цену
// существующей (семантика HTTP PUT). Учёт отдельных сделок с пересчётом
// средней цены — отдельная задача на будущее.
func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, upsertPosition,
		arg.PortfolioID,
		arg.Ticker,
		arg.Quantity,
		arg.AvgPrice,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Ticker,
		&i.Quantity,
		&i.AvgPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
